# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2be4d23c3df86266f34bdf77bccda25"
name = "ReviewLift"
application_url = "https://ecom-review-app.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_files,write_files,read_orders,read_customers,write_customers,write_discounts"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[auth]
redirect_urls = [ "https://ecom-review-app.onrender.com/api/auth" ]

[app_proxy]
url = "https://ecom-review-app.onrender.com/api/reviews"
subpath = "reviews"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
